### PR TITLE
Follow naming conventions for Composite and Claims XIAMPolicy

### PR DESCRIPTION
**Pull request by csantanapr**
### What does this PR do?

Follow naming conventions for Composite and Claims XIAMPolicy

### Motivation

Found out that this is the only composite from the package not following the convention for naming Composite Resources (XR)

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)

- [ ] Yes, I have added a new example under [examples](https://github.com/aws-samples/crossplane-aws-blueprints/tree/main/examples) to support my PR

- [ ] Yes, I have updated the [docs](https://github.com/aws-samples/crossplane-aws-blueprints/tree/main/doc) for this feature

- [ ] Yes, I have linked to an issue or feature request (applicable to PRs that solves a bug or a feature request)

**Note**:
 - Not all the PRs require examples and docs
 - We prefer small, well tested pull requests. Please ensure your pull requests are self-contained, and commits are squashed

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by nimakaviani — COMMENTED** [review]
LGTM

**Comment by nabuskey** [comment]
IAM policy compositions are not meant to be claimed, they are meant to be part of another composition. Thus it doesn't follow the naming convention.

**Comment by nimakaviani** [comment]
I dont think it hurts for them to follow the naming convention tho. any particular concerns around having them named similarly?

**Comment by nabuskey** [comment]
Yeah that's fine, but the XRD needs not updated for supporting claims.

**Comment by csantanapr** [comment]
@nimakaviani @nabuskey PTAL when you have a chance I addressed the review feedback
Removed the claim capability

**Review by nabuskey — APPROVED** [review]
LGTM Thank you very much!

**Pull request merged**
