### PR TITLE
feat: Updates across bootstrap and compositions

### PR DESCRIPTION
**Pull request by csantanapr**
### What does this PR do?

Updates the terraform example to be consistent with [terraform-aws-eks-blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1220) crossplane module.

### Motivation

While reviewing the examples noticed some inconsistencies.
- Make the main.tf example simpler and just do the minimum to show crossplane
- Remove references to terrajet provider (deprecated)
- Fix example not failing because of not finding provider config for aws and kubernetes

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)

- [ ] Yes, I have added a new example under [examples](https://github.com/aws-samples/crossplane-aws-blueprints/tree/main/examples) to support my PR

- [x] Yes, I have updated the [docs](https://github.com/aws-samples/crossplane-aws-blueprints/tree/main/doc) for this feature

- [ ] Yes, I have linked to an issue or feature request (applicable to PRs that solves a bug or a feature request)

**Note**:
 - Not all the PRs require examples and docs
 - We prefer small, well tested pull requests. Please ensure your pull requests are self-contained, and commits are squashed

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by csantanapr** [comment]
This PR depends on terraform PR https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1220

**Comment by nabuskey** [comment]
This PR touches too many different areas. Please break it up into smaller PRs.

**Comment by csantanapr** [comment]
@nabuskey I can try but some parts are inter dependent, merging a small PR can cause some of the example not to be in working state

**Comment by nimakaviani** [comment]
+1 on @nabuskey 's suggestion. 

if we keep each PR self-contained it will be easier to track changes and potentially revert if and where needed.  @csantanapr 
 if you can split this into some logically sound and separate PRs, that'd be great!

**Comment by csantanapr** [comment]
I will start working on braking the PR in parts

**Comment by csantanapr** [comment]
I split the PR into a series of smaller PRs
https://github.com/awslabs/crossplane-on-eks/pull/70
https://github.com/awslabs/crossplane-on-eks/pull/71
https://github.com/awslabs/crossplane-on-eks/pull/72
https://github.com/awslabs/crossplane-on-eks/pull/73
https://github.com/awslabs/crossplane-on-eks/pull/74
https://github.com/awslabs/crossplane-on-eks/pull/75
https://github.com/awslabs/crossplane-on-eks/pull/76
https://github.com/awslabs/crossplane-on-eks/pull/77
https://github.com/awslabs/crossplane-on-eks/pull/78
https://github.com/awslabs/crossplane-on-eks/pull/79

**Pull request closed without merging**
